# fly.toml app configuration file generated for proxy-acroworldtour-com on 2024-06-11T08:17:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proxy-acroworldtour-com'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "nginxcache"
  destination = "/cache"
