name: Deploy to prod
on:
  push:
    branches:
      - main
jobs:
  deploy-api-fly-io:
    name: Deploy API to fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile Dockerfile.fly.io
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-api-render-com:
    name: Deploy API to render.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.3.2
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
          api_key: ${{ secrets.RENDER_API_KEY }} # required
          clear_cache: false # Clear build cache. Optional
          wait_deploy: false # Wait until the deploy status is successful. Warning! Free Render services can take +5 minutes to be fully deployed. Optional
